### ISSUE TITLE
Python3IDE on ipad

### ISSUE THREAD

**Issue by Giusseppel** [mh0717/Python3AI#1]
Hi, I am using Python3IDE on my iPad Pro and although it runs my python scripts I cannot find a way to work line by line from a console. I am teaching turtle and need students to be able to write a line , hit return and see the result in a window. I can do this with python launcher on my Mac but cannot work out how to bring up a python console on the iPad. Any advice would be appreciated.
Giusseppe

**Comment by mh0717** [comment]
hello, we fixed it in version 1.2.6
new file -> turtle interactive
